# Generated by Django 4.0.4 on 2022-05-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0008_alter_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_category',
            field=models.CharField(blank=True, choices=[('Internet Shop', 'Alser.kz'), ('SuperMarket', 'Mechta.kz'), ('Shopping center', 'Sulpak.kz'), ('Furniture Shop', 'Technodom.kz'), ('IT Company', 'Fora.kz'), ('Educational Center', 'Tgrad.kz')], max_length=40),
        ),
    ]
