# Generated by Django 4.1.3 on 2022-11-14 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbook', '0009_alter_company_comapny_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_category',
            field=models.CharField(blank=True, choices=[('Internet Shop', 'Қолға арналған лак'), ('SuperMarket', 'Макияж щеткасы'), ('Shopping center', 'Көзге арналған тень'), ('Furniture Shop', 'Бетке арналған опадалап'), ('IT Company', 'Көзге арналған тушь'), ('Educational Center', 'Ерін памадасы')], max_length=40),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
