# Generated by Django 4.1.3 on 2022-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0010_alter_company_comapny_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_category',
            field=models.CharField(blank=True, choices=[('Internet Shop', '3 жас'), ('SuperMarket', '4 жас'), ('Shopping center', '5 жас'), ('Furniture Shop', '6 жас'), ('IT Company', 'Қосымша ақпарат'), ('Educational Center', 'Жаңалықтар')], max_length=40),
        ),
    ]
