# Generated by Django 4.1.3 on 2022-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0011_alter_company_comapny_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_category',
            field=models.CharField(blank=True, choices=[('Internet Shop', '3 жас'), ('SuperMarket', '4 жас'), ('Shopping center', '5 жас'), ('Furniture Shop', '6 жас'), ('IT Company', 'Қосымша ақпарат'), ('Educational Center', 'Жаңалықтар')], max_length=40, verbose_name='Қай жасқа арналған'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_about',
            field=models.TextField(blank=True, verbose_name='Курс сипаттамасы'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Сурет орналастыру'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Курс тақырыбы'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Байланыс'),
        ),
    ]
