# Generated by Django 4.1.3 on 2022-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0014_alter_rate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_video',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Видео орналастыру'),
        ),
    ]
