# Generated by Django 4.1.5 on 2023-01-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0018_remove_questionmodel_image_questionmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='company',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, to='handbook.company'),
            preserve_default=False,
        ),
    ]
